# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "tg2mx-bot"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
dotenvy = "0.15"
log = "0.4"
matrix-sdk = { version = "0.6", features = ["rustls-tls"], default-features = false }
pretty_env_logger = "0.4"
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["log"] }
