# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "tg2mx-bot"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
dotenvy = "0.15"
indoc = "2.0"
log = "0.4"
once_cell = "1.9"
pretty_env_logger = "0.4"
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["log"] }

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "5dbee7dcdc2bfd0a46ec883ba1b88faa412582e3"
features = ["rustls-tls"]
default-features = false
