# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "tg2mx-bot"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
ruma = { version = "0.7", features = ["client-ext-client-api", "client-reqwest-rustls-webpki-roots"] }
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }
