name: Rust

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: "always"
  RUST_BACKTRACE: "1"
  RUST_LOG: "info"
  # speed up build by using clang/lld
  CC: "clang-14"
  CXX: "clang++-14"
  LD: "clang-14"
  LDFLAGS: "-fuse-ld=lld-14"
  RUSTFLAGS: "-C linker=clang-14 -C link-arg=-fuse-ld=lld-14"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - toolchain: "stable"
          - toolchain: "nightly"
    name: "Test (Rust ${{matrix.rust.toolchain}})"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: msrd0/install-rlottie-action@v1
      - run: sudo apt update -y && sudo apt install -y libavdevice-dev
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{matrix.rust.toolchain}}"
        id: "rust-toolchain"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}}"

      - run: cargo test --workspace --locked

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rlottie system library
        uses: msrd0/install-rlottie-action@v1
      - name: Install package dependencies
        run: sudo apt update -y && sudo apt install -y libavdevice-dev
      - name: Build
        run: cargo build --verbose --release
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: tg2mx-bot
          path: target/release/tg2mx-bot

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tg2mx-bot
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BINARY=tg2mx-bot

      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see "[AUTOTITLE](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds)."
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
